export const small_vectors = [
  "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Projects/HelpPage/BubbleShoveler/English/Fuji_Bubble_8Languages_en_US_updated_1x._CB445837675_.png",
  "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_Currency_en_US_1X._CB451228332_.jpg",
  "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_SecurePayment_en_US_1X._CB451228335_.jpg",
  "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_ImportFees_en_US_1X._CB451228332_.jpg",
  "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_TrackPackage_en_US_1X._CB451228335_.jpg",
  "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/October/BubbleShoveler/AIS_Bubble_247CS_en_US_1X._CB451228332_.jpg",
];
export const images_1 = [
  "https://images-na.ssl-images-amazon.com/images/I/11tEFlSGn6L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41TEawIMRfL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/310bMKQjT5L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41WOalZ1N5L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41ehOZgmMML._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51EXcNKQgoL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31k5umXBg9L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/413BYCci6NL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/4178UF1W9NL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31YGiracCNL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41Lv8P3IcVL._AC_SY200_.jpg",
];

export const images_3 = [
  "https://images-na.ssl-images-amazon.com/images/I/41RGrXACv8L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51rJTG4++AL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41+tceVy64L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31WLusUnqkL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31BrpSyGV3L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51G6gwpEvdL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51roA9wBHJL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41b5I86kihL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51Fo-wDkh2L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/416YuRmcsNL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41g-gVqoCaL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31mPokRaXvL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/310cWWGXoBL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31eP4P23zkL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31fx5WTzQaL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41VT5E58UOL._AC_SY200_.jpg",
];

export const images_2 = [
  "https://images-na.ssl-images-amazon.com/images/I/31pEe2taIPL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41kaOFDXzSL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/517J1Mfca0L._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31AZvhYLyeL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51YWlGN4cuL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41LO2OX6pRL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/31i3tpuXxxL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51TucFenMAL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/415-s5FkXIL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41fVBsNMNmL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41mCozLA9CL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41XcLWH8nYL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51INjwoZOsL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/41GGPRqTZtL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51-3DH9QFrL._AC_SY200_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/51cqTo2C6LL._AC_SY200_.jpg",
];
